### ISSUE TITLE
Real image projection of Structured Noise Injection?

### ISSUE THREAD

**Issue by Annonymous-repos** [naver-ai/StyleMapGAN#10]
How do you project an image into the latent space of Structured Noise[3] in Table 3?

**Comment by blandocs** [comment]
We changed [the stylegan2 projector code](https://github.com/NVlabs/stylegan2/blob/master/projector.py) to fit the Structured Noise Injection structure. 

We don't have to change many things and other settings are the same as the stylegan2 projector.

**Comment by Annonymous-repos** [comment]
Thanks.
