### ISSUE TITLE
Questions about metrics for reconstruction

### ISSUE THREAD

**Issue by Annonymous-repos** [naver-ai/StyleMapGAN#12]
Hello, thanks for sharing your code. I'm very interested in your work and I got a question when I run the metrics for reconstruction. The output of metrics.reconstruction  are **0.015**(mse)  and  **0.214**(lpips). The output seems much better than the results reported in Table 3 in the paper (mse=**0.024**, lpips=**0.242**).  I would appreciate it if you could give me an explanation.
![image](https://user-images.githubusercontent.com/56380327/126290545-a0c504a1-067c-45f5-a091-40575558d61d.png)

**Comment by blandocs** [comment]
Thank you for your interest :)

We publish the pretrained networks with further training.
The paper shows a 5M-image-trained result but we publish a 20M-image-trained model.

Please refer to this [comment](https://github.com/naver-ai/StyleMapGAN/issues/8#issuecomment-883019888).

**Comment by Annonymous-repos** [comment]
Thanks for your reply.

**Comment by Annonymous-repos** [comment]
> Thank you for your interest :)
> 
> We publish the pretrained networks with further training.
> The paper shows a 5M-image-trained result but we publish a 20M-image-trained model.
> 
> Please refer to this [comment](https://github.com/naver-ai/StyleMapGAN/issues/8#issuecomment-883019888).

Would you mind providing the 5M-image-trained model?

**Comment by blandocs** [comment]
> > Thank you for your interest :)
> > We publish the pretrained networks with further training.
> > The paper shows a 5M-image-trained result but we publish a 20M-image-trained model.
> > Please refer to this [comment](https://github.com/naver-ai/StyleMapGAN/issues/8#issuecomment-883019888).
> 
> Would you mind providing the 5M-image-trained model?

Please refer to this [commit](https://github.com/naver-ai/StyleMapGAN/commit/66a1898504ba9620ab366e7a0734c0181ccec3f6) :)

**Comment by Annonymous-repos** [comment]
Thanks a lot :)
