### ISSUE TITLE
Fail to open demo

### ISSUE THREAD

**Issue by berylsheep-up** [naver-ai/StyleMapGAN#13]
Thanks for the excellent work!

I am failed to run the demo on my local machine. The app does not produce the wrong information and the website seems can not load the demo images. Can you help me to fix it?

I can run all the commands except the demo one such as the unaligned transplantation command.

![screenshot0](https://user-images.githubusercontent.com/60908385/128677012-73e71350-3565-4792-b740-2b7a819336e6.png)
![screenshot1](https://user-images.githubusercontent.com/60908385/128677022-5961a9ef-d2df-4c88-8c0b-e48add4bb570.png)

**Comment by blandocs** [comment]
Hi :)
It seems that there aren't any sample images.
Would you check the path (demo/static/components/img) and the browser debug console?

My test browser was chrome.

![image](https://user-images.githubusercontent.com/11532292/128708169-41ae7b2e-cf28-4f32-b736-62e06571ad33.png)

**Comment by berylsheep-up** [comment]
Thanks for reply!

There are wrong messages in the debug console.
It failed to load the resource.
Both the firefox and chrome browser produce the similar wrong messages.
![Selection_067](https://user-images.githubusercontent.com/60908385/128804204-45703dc7-7c45-4e94-990a-004337a891f8.png)

**Comment by berylsheep-up** [comment]
Thanks for reply!

There are wrong messages in the debug console.
It failed to load the resource.
Both the firefox and chrome browser produce the similar wrong messages.
![Selection_067](https://user-images.githubusercontent.com/60908385/128804204-45703dc7-7c45-4e94-990a-004337a891f8.png)

**Comment by berylsheep-up** [comment]
Thanks for reply! 
Problem solved after turning to chrome.
