### ISSUE TITLE
Pre-trained weights download link is invalid.

### ISSUE THREAD

**Issue by wmpscc** [naver-ai/StyleMapGAN#15]
Hi, thank you for sharing your work. I can't download weight through script, please check.

**Comment by nguyenquyem99dt** [comment]
I also have the same issue.

**Comment by cyrilzakka** [comment]
Same. `ERROR 403: Forbidden` when running `bash download.sh download-pretrained-network-256 celeba_hq`

**Comment by blandocs** [comment]
I updated the expired date, thanks :)
Please try again 👍

**Comment by wmpscc** [comment]
@blandocs 
Thank you for your update, but the link below is still invalid.
```
celeba_hq_5M
https://mysnu-my.sharepoint.com/:u:/g/personal/gustnxodjs_seoul_ac_kr/ERjs1Hj0vvJPiQ6d-Yew_qsBi9c-PT-xZygSeO-Nvixeug?e=SzeeJb&download=1
afhq_5M
https://mysnu-my.sharepoint.com/:u:/g/personal/gustnxodjs_seoul_ac_kr/EebeiMTHbK5Irw1allTdp0oBgpu_m8AXOJPqNYe1m5nJPw?e=xu1TlH&download=1
```

**Comment by blandocs** [comment]
> @blandocs
> Thank you for your update, but the link below is still invalid.
> 
> ```
> celeba_hq_5M
> https://mysnu-my.sharepoint.com/:u:/g/personal/gustnxodjs_seoul_ac_kr/ERjs1Hj0vvJPiQ6d-Yew_qsBi9c-PT-xZygSeO-Nvixeug?e=SzeeJb&download=1
> afhq_5M
> https://mysnu-my.sharepoint.com/:u:/g/personal/gustnxodjs_seoul_ac_kr/EebeiMTHbK5Irw1allTdp0oBgpu_m8AXOJPqNYe1m5nJPw?e=xu1TlH&download=1
> ```

Oh, I forget those networks.
Please check once more, thanks :)

**Comment by chLFF** [comment]
@blandocs Can you please update the download links? The links are expired again. Thank you very much.
