### ISSUE TITLE
Download.sh updated link points to possibly corrupted models

### ISSUE THREAD

**Issue by BigBenPost** [naver-ai/StyleMapGAN#20]
I downloaded the pre-trained networks using the updated download.sh files, and pytorch is unable to load them, giving the following error: _pickle.UnpicklingError: invalid load key, ‘<‘

I suspect that the pre-trained network on the google drive is corrupted. Could you check whether it is the case?

**Comment by BigBenPost** [comment]
It was due to version control on my local machine. Sorry for the inconvenience.

**Comment by josejhlee** [comment]
How did you fix it @mushroomsc ? I am using a server and downloading directly in it doesnt work. So Im manually getting from the google drive link and transfering to the server from local via scp. What did you come up with?
