### ISSUE TITLE
UnpicklingError: invalid load key, '<'. 

### ISSUE THREAD

**Issue by josejhlee** [naver-ai/StyleMapGAN#27]
Hello authors,

I have an error when using the pretrained checkpoints when ```torch.load(args.ckpt)``` is run in generate.py (or any piece of code with the function). I tried re-downloading the model as proposed in this [issue](https://github.com/CSAILVision/places365/issues/49).
The only change I made to accommodate my CUDA 11 version was to instal pytorch with ```conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch```. Thanks for you attention, it is much appreciated.

**Comment by josejhlee** [comment]
Solved by manually downloading through the google drive link!

**Comment by brando90** [comment]
related: https://github.com/learnables/learn2learn/issues/310

**Comment by chLFF** [comment]
> Solved by manually downloading through the google drive link!

Can you plz share the google drive link or the checkpoints file? The links in download.sh are disabled. And i can not find  the google drive link.

**Comment by josejhlee** [comment]
@chLFF I am able to open the links without a problem. Which want do you want? And do the authors consent in this?

**Comment by chLFF** [comment]
@josejhlee The link says 'i'm sorry. the link has expired.' I want celeba_hq_256_8x8.pt and celeba_hq_5M_256_8x8.pt, thank you. I didn't get consent yet but i think this work is open-source.

**Comment by josejhlee** [comment]
@chLFF
Yeah, doesn't seem like they closed on purpose.
Let me know if these are the ones that you asked for.
celeba_hq_8x8_20M_revised
https://drive.google.com/file/d/1BCvVb8ipydQMFU4ZsuMcW3pKSubtALd3/view?usp=sharing
celeba_hq_8x8_5M_revised:
https://drive.google.com/file/d/17OxdwVK--WjZXrHe1iupMQSP9VscaHm0/view?usp=sharing

**Comment by chLFF** [comment]
@josejhlee 'celeba_hq_8x8_20M_revised' is one of i need, thanks! Do you have 5M-image-trained model of CelebA-256? I believe its name is celeba_hq_5M_256_8x8.pt.

**Comment by josejhlee** [comment]
@chLFF My bad, I edited the link above!

**Comment by chLFF** [comment]
@josejhlee This helps me a lot, thank you! 고맙다!
