### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by ykk648** [naver-ai/StyleMapGAN#4]
![图片](https://user-images.githubusercontent.com/19514053/117416134-a58fba00-af4b-11eb-94ab-cd1f372e4ce7.png)

How much GPU memory does I need to launch demo.py?

**Comment by Radium98** [comment]
Do you encounter the problem“ImportError: /home/f403/.cache/torch_extensions/fused/fused.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE” when you run demo.py? Can you leave your email address I want to ask something about this project.
![Uploading image.png…]()

**Comment by ykk648** [comment]
@Radium98 
It looks like some kind of 'Environment' issue, follow [install.sh](https://github.com/naver-ai/StyleMapGAN/blob/main/install.sh), the only different is that I use cuda-11.1 and pytorch-1.8.

**Comment by Radium98** [comment]
Have you run the demo.py successfully ?

**Comment by ykk648** [comment]
I tried afhq instead of celeba_hq, CUDA out of memory again.

**Comment by Radium98** [comment]
It's really frustrating，and I don't know how to process my own data to feed it into the network. Have you solved this problem ?

**Comment by blandocs** [comment]
@cloisonne GPU consumption mostly depends on input image sizes and _interpolation_step_ argument. Please use smaller _interpolation_step_ or input size (pretrained model).

**Comment by blandocs** [comment]
> Do you encounter the problem“ImportError: /home/f403/.cache/torch_extensions/fused/fused.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE” when you run demo.py? Can you leave your email address I want to ask something about this project.

I'm not sure the reason for your problem. Cuda and Pytorch environment may differ from ours.

**Comment by blandocs** [comment]
> It's really frustrating，and I don't know how to process my own data to feed it into the network. Have you solved this problem ?

I just replied. Please check your previous issue :)
