### ISSUE TITLE
How many iterations do you use to train the model

### ISSUE THREAD

**Issue by zhang-lingyun** [naver-ai/StyleMapGAN#8]
Thank you for publishing the code. Your work is very impressive. I wonder how many iterations do you use to train the model？I noticed that the default is 1,400,000. Is this value for all your training datasets? 1400000 training iterations a bit too long, I am curious if there is a small number of training iteration.

**Comment by blandocs** [comment]
Thank you for your interest in our work and sorry for the late reply.

In the experiments of the paper, all StyleMapGAN variants at 256 x 256 are trained for two weeks on 5M images with 2 Tesla V100 GPUs using a minibatch size of 16. So it's about **320K iterations**. Please refer to the _Training_ section in Appendix C (Implementation details).

We offered [the pretrained networks](https://github.com/naver-ai/StyleMapGAN/blob/main/download.sh) trained on 20M images for better reconstruction results. But the 5M-trained-network is enough for reconstruction and better in a random generation.

**Comment by zhang-lingyun** [comment]
thanks for your reply
